# HTTP Status Codes 示例配置
default_language: zh-CN
fallback_language: en
locales_path: locales
debug: true
enable_metrics: false
enable_watcher: false

# 语言文件配置
locale_config:
  mode: "flat"
  languages: ["zh-CN", "en"]

# 响应码配置
response_config:
  load_builtin: true
  auto_init: true

# 缓存配置
cache:
  enable: true
  ttl: 3600
  size: 1000
  l2_size: 10000
  enable_file: false

# 对象池配置
pool:
  enable: true
  size: 100
  warm_up: true
  languages: ["zh-CN", "en"]